# Generated by Django 5.0.6 on 2026-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_appointment_appointment_unique_active_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("start", models.CharField(max_length=20)),
                ("end", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("stack_tags", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-start"],
            },
        ),
    ]
