# Generated by Django 5.0.6 on 2026-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_experience"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
